2022-07-08 20:41:11,578 INFO    MainThread:14676 [wandb_setup.py:_flush():76] Loading settings from C:\Users\julio\.config\wandb\settings
2022-07-08 20:41:11,578 INFO    MainThread:14676 [wandb_setup.py:_flush():76] Loading settings from C:\Users\julio\Downloads\trabalho 2(mlops)\Example_04\wandb\settings
2022-07-08 20:41:11,578 INFO    MainThread:14676 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2022-07-08 20:41:11,578 WARNING MainThread:14676 [wandb_setup.py:_flush():76] Could not find program at -m __main__
2022-07-08 20:41:11,578 INFO    MainThread:14676 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': None, 'program': '-m __main__'}
2022-07-08 20:41:11,579 INFO    MainThread:14676 [wandb_init.py:_log_setup():428] Logging user logs to C:\Users\julio\Downloads\trabalho 2(mlops)\Example_04\wandb\run-20220708_204111-gh7hgeqd\logs\debug.log
2022-07-08 20:41:11,579 INFO    MainThread:14676 [wandb_init.py:_log_setup():429] Logging internal logs to C:\Users\julio\Downloads\trabalho 2(mlops)\Example_04\wandb\run-20220708_204111-gh7hgeqd\logs\debug-internal.log
2022-07-08 20:41:11,579 INFO    MainThread:14676 [wandb_init.py:init():462] calling init triggers
2022-07-08 20:41:11,579 INFO    MainThread:14676 [wandb_init.py:init():465] wandb.init called with sweep_config: {}
config: {}
2022-07-08 20:41:11,579 INFO    MainThread:14676 [wandb_init.py:init():515] starting backend
2022-07-08 20:41:11,580 INFO    MainThread:14676 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2022-07-08 20:41:11,588 INFO    MainThread:14676 [backend.py:ensure_launched():217] starting backend process...
2022-07-08 20:41:11,707 INFO    MainThread:14676 [backend.py:ensure_launched():222] started backend process with pid: 5996
2022-07-08 20:41:11,708 INFO    MainThread:14676 [wandb_init.py:init():525] backend started and connected
2022-07-08 20:41:11,710 INFO    MainThread:14676 [wandb_init.py:init():596] updated telemetry
2022-07-08 20:41:11,714 INFO    MainThread:14676 [wandb_init.py:init():627] communicating run to backend with 30 second timeout
2022-07-08 20:41:14,184 INFO    MainThread:14676 [wandb_run.py:_on_init():1924] communicating current version
2022-07-08 20:41:14,291 INFO    MainThread:14676 [wandb_run.py:_on_init():1928] got version response upgrade_message: "wandb version 0.12.21 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-07-08 20:41:14,291 INFO    MainThread:14676 [wandb_init.py:init():662] starting run threads in backend
2022-07-08 20:41:19,315 INFO    MainThread:14676 [wandb_run.py:_console_start():1898] atexit reg
2022-07-08 20:41:19,316 INFO    MainThread:14676 [wandb_run.py:_redirect():1771] redirect: SettingsConsole.WRAP
2022-07-08 20:41:19,316 INFO    MainThread:14676 [wandb_run.py:_redirect():1808] Wrapping output streams.
2022-07-08 20:41:19,318 INFO    MainThread:14676 [wandb_run.py:_redirect():1832] Redirects installed.
2022-07-08 20:41:19,318 INFO    MainThread:14676 [wandb_init.py:init():688] run started, returning control to user process
2022-07-08 20:41:23,224 INFO    MainThread:14676 [wandb_run.py:_atexit_cleanup():1867] got exitcode: 0
2022-07-08 20:41:23,225 INFO    MainThread:14676 [wandb_run.py:_restore():1839] restore
2022-07-08 20:41:23,894 INFO    MainThread:14676 [wandb_run.py:_restore():1839] restore
2022-07-08 20:41:31,299 ERROR   MainThread:14676 [wandb_run.py:_atexit_cleanup():1888] Problem finishing run
Traceback (most recent call last):
  File "C:\Users\julio\anaconda3\lib\site-packages\wandb\sdk\wandb_run.py", line 1876, in _atexit_cleanup
    self._on_finish()
  File "C:\Users\julio\anaconda3\lib\site-packages\wandb\sdk\wandb_run.py", line 1987, in _on_finish
    self._footer_exit_status_info(
  File "C:\Users\julio\anaconda3\lib\site-packages\wandb\sdk\wandb_run.py", line 2901, in _footer_exit_status_info
    printer.display(f'{" ".join(info)}')
  File "C:\Users\julio\anaconda3\lib\site-packages\wandb\sdk\lib\printer.py", line 35, in display
    self._display(text, status=status)
  File "C:\Users\julio\anaconda3\lib\site-packages\wandb\sdk\lib\printer.py", line 90, in _display
    wandb.termlog(text)
  File "C:\Users\julio\anaconda3\lib\site-packages\wandb\errors\term.py", line 40, in termlog
    _log(
  File "C:\Users\julio\anaconda3\lib\site-packages\wandb\errors\term.py", line 96, in _log
    click.echo(line, file=sys.stderr, nl=newline)
  File "C:\Users\julio\anaconda3\lib\site-packages\click\utils.py", line 298, in echo
    file.write(out)  # type: ignore
  File "C:\Users\julio\anaconda3\lib\site-packages\click\_compat.py", line 550, in _safe_write
    return _write(s)
  File "C:\Users\julio\anaconda3\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\julio\anaconda3\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\julio\anaconda3\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\julio\anaconda3\lib\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
ValueError: I/O operation on closed file.
